version: "3.9"

services:

  mysql:

    image: mysql:8.4

    container_name: mysql-db

    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - app-network

  backend:

    build:
      context: ./backend

    container_name: springboot-app

    restart: unless-stopped

    depends_on:
      - mysql

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "8081:8081"

    networks:
      - app-network

  frontend:

    build:
      context: ./frontend

    container_name: react-app

    restart: unless-stopped

    ports:
      - "3000:80"

    depends_on:
      - backend

    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network: